name: Auto merge release Pull Request

on:
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.find_pr.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find release PRs
        uses: actions/github-script@v7
        id: find_pr
        with:
          script: |
            const script = require('./.github/scripts/find-release-prs.js');
            await script({github, context, core});

      - name: git-flow merge
        uses: yanamura/git-flow-merge-action@v1 # https://github.com/yanamura/git-flow-merge-action
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ steps.find_pr.outputs.branch_name }}
          develop_branch: "develop"
          main_branch: "main"
        id: merge
