name: Prepare app for release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump Type(minor or major)'
        required: true
        default: 'minor'

jobs:
  prepare_release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # https://github.com/actions/checkout#checkout-v5
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # https://github.com/actions/setup-ruby
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install # install gems in the Gemfile

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          bundle exec fastlane prepare_release bump_type:${{ github.event.inputs.bump_type }}
