name: Build and submit release app

on:
  pull_request:
    types: closed
    branches:
      - main
  workflow_dispatch:

jobs:
  submit:
    runs-on: macos-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Set up GoogleService-Info.plist
        run: |
          RESOURCE_DIR="buntan/Resource"
          mkdir -p "$RESOURCE_DIR"
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_CONTENT }}" | base64 -d > "$RESOURCE_DIR/GoogleService-Info.plist"

      - name: Build and submit release app
        env:
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 600
        run: |
          bundle install
          bundle exec fastlane release

